server:
  port: 8899
  servlet:
    context-path: /api

spring:
  application:
    name: document-service
  datasource:
    url: jdbc:postgresql://localhost:5433/fletrax_tracking
    username: fletrax_user
    password: fletrax_password
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect
document:
  storage-path: "/secure/documents"
  file-validation-enabled: true   # Set this to false to disable file validation
  max-file-size: 10485760  # 10MB in bytes
  allowed-extensions:
     - jpg
     - jpeg
     - png
     - pdf
  allowed-content-types:
     - image/jpeg
     - image/png
     - application/pdf